export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_SINGLE_MOVIE = 'FETCH_SINGLE_MOVIE';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR'
export const LOADING = 'LOADING';